gvi/gvi/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^reports/', include('reports.urls', namespace='reports', app_name='reports')),
    url(r'^budgets/', include('budgets.urls', namespace='budgets', app_name='budgets')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts', app_name='accounts')),
    url(r'^transactions/', include('transactions.urls', namespace='transactions', app_name='transactions')),
    url(r'^hubs/', include('hubs.urls', namespace='hubs', app_name='hubs')),
    url(r'^users/', include('users_m.urls', namespace='users_m', app_name='users_m')),
    url(r'^admin/', include(admin.site.urls)),
]

gvi/transactions/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^search_transactions/$', views.search_transactions, name='search_transactions'),
    url(r'^transaction/account/(?P<pk>\d+)/$', views.balance_detail, name='balance_detail'),
    url(r'^transaction/account/(?P<pk>\d+)/new_transaction/$', views.new_transaction, name='new_transaction'),
    url(r'^transaction/account/(?P<pk>\d+)/change_transaction/$', views.update_delete_transaction,
        name='change_transaction'),
    url(r'^cats_subs/$', views.cats_subs, name='cats_subs'),
    url(r'^new_subcategory/$', views.new_del_sub, name='change_sub'),
    url(r'^subcategories/$', views.subcategories, name='subcategories'),
]

gvi/transactions/models.py
from django.db import models
from django.utils import timezone


class Category(models.Model):
    name = models.CharField(max_length=50)
    number = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return str(self.name) + ":" + str(self.number)

    def subs(self):
        sub_list = []
        ss = Subcategory.objects.filter(category=self)
        for s in ss:
            sub_list.append(s.name)
        return sub_list

    @classmethod
    def to_dict(cls):
        cats = cls.objects.all()
        le_dict = {}
        for cat in cats:
            le_dict[cat.name] = cat.subs()
        return le_dict


class Subcategory(models.Model):
    name = models.CharField(max_length=50)
    category = models.ForeignKey(Category)

    def __str__(self):
        return self.name


class Transaction(models.Model):
    IN = 'i'
    OUT = 'o'
    TYPE_CHOICES = (
        (IN, 'Money In'),
        (OUT, 'Money Out'),
    )
    transaction_type = models.CharField(max_length=5, choices=TYPE_CHOICES, default=OUT)
    category = models.ForeignKey(Category, blank=True, null=True)
    date = models.DateField()
    subcategory = models.ForeignKey(Subcategory, blank=True, null=True)
    comment = models.CharField(max_length=200, blank=True)
    amount = models.DecimalField(decimal_places=2, max_digits=19)
    balance = models.DecimalField(decimal_places=2, max_digits=19)
    account = models.ForeignKey('accounts.Account')

    def __str__(self):

        return self.transaction_type + str(self.amount)

    @classmethod
    def first_year(cls):
        years = cls.objects.order_by('date')[0].date.year
        return years

    @classmethod
    def year_range(cls):
        year_range = [cls.first_year()]

        if timezone.now().year == year_range[-1]:
            return year_range
        else:
            while year_range[-1] != timezone.now().year:
                year_range.append(year_range[-1] + 1)
            return year_range

        return 'Critical Error'

gvi/transactions/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404, JsonResponse, HttpResponseServerError
from django.views.decorators.csrf import csrf_exempt

from .models import Transaction, Category, Subcategory
from accounts.models import Account, Currency

from decimal import *


def index(request):
    transactions = Transaction.objects.order_by('-date')
    category = Category.objects.all()
    subcategory = Subcategory.objects.all()

    bank_accounts = Account.objects.filter(account_type='b')
    cash_accounts = Account.objects.filter(account_type='c')
    currencies = Currency.objects.all()

    context = {'transactions': transactions,
               'category': category,
               'subcategory': subcategory,
               'bank_acc': bank_accounts,
               'cash_acc': cash_accounts,
               'currencies': currencies,
               }

    return render(request, 'transactions/dashboard.html', context)


def search_transactions(request):
    print "**********"
    print request.body
    print "**********"
    enableCategory = request.POST.get('enableCategory')
    enableSubcategory = request.POST.get('enableSubcategory')
    if enableCategory and enableSubcategory:
        categorySelect = request.POST.get('categorySelect')
        subcategorySelect = request.POST.get('subcategorySelect')
        fromDate = request.POST.get('fromDate')
        toDate = request.POST.get('toDate')
        transactions = Transaction.objects.filter(category__name=categorySelect)
        transactions = transactions.filter(subcategory__name=subcategorySelect)
        transactions = transactions.filter(date__range=[fromDate, toDate]).order_by('-date')

    elif enableCategory:
        fromDate = request.POST.get('fromDate')
        toDate = request.POST.get('toDate')
        categorySelect = request.POST.get('categorySelect')
        transactions = Transaction.objects.filter(category__name=categorySelect)
        transactions = transactions.filter(date__range=[fromDate, toDate]).order_by('-date')

    else:
        fromDate = request.POST.get('fromDate')
        toDate = request.POST.get('toDate')
        transactions = Transaction.objects.filter(date__range=[fromDate, toDate]).order_by('-date')

    category = Category.objects.all()
    subcategory = Subcategory.objects.all()
    context = {'transactions': transactions,
               'category': category,
               'subcategory': subcategory,
               }

    return render(request, 'transactions/b_detail.html', context)


def balance_detail(request, pk):
    transactions = Transaction.objects.order_by('-date')
    category = Category.objects.all()
    subcategory = Subcategory.objects.all()

    bank_accounts = Account.objects.filter(account_type='b')
    cash_accounts = Account.objects.filter(account_type='c')
    currencies = Currency.objects.all()
    account = get_object_or_404(Account, pk=pk)

    context = {'a': account,
               'category': category,
               'subcategory': subcategory,
               'transactions': transactions}
    return render(request, 'transactions/b_detail.html', context)


@csrf_exempt
def new_transaction(request, pk):
    if request.is_ajax():
        if request.method == 'POST':
            try:
                t_type = request.POST['type']
                cat = request.POST['category']
                sub = request.POST.get('subcategory')
                date = request.POST['date']
                comment = request.POST['comment']
                amount = request.POST['amount']
                category = Category.objects.get(name=cat)
                if sub:
                    subcategory = Subcategory.objects.get(name=sub)
                account_id = request.POST['id']
                account = get_object_or_404(Account, pk=account_id)

                if t_type == 'i':
                    account.balance += Decimal(float(amount))
                else:
                    account.balance -= Decimal(float(amount))
                account.save()
                if sub:
                    transaction = Transaction(transaction_type=t_type, category=category, subcategory=subcategory,
                                              comment=comment, amount=amount, balance=account.balance, date=date,
                                              account=account)
                else:
                    transaction = Transaction(transaction_type=t_type, category=category,
                                              comment=comment, amount=amount, balance=account.balance, date=date,
                                              account=account)

                transaction.save()

                return JsonResponse({'code': '200',
                                     'msg': 'transaction added'})

            except KeyError as e:
                pass
        if request.method == 'GET':
            try:
                t_id = request.GET['id']
                transaction = get_object_or_404(Transaction, pk=t_id)
                if transaction.subcategory:
                    context = {'id': transaction.pk,
                               'type': transaction.transaction_type,
                               'category': transaction.category.name,
                               'subcategory': transaction.subcategory.name,
                               'date': transaction.date,
                               'amount': transaction.amount,
                               'comment': transaction.comment,
                               }
                else:
                    context = {'id': transaction.pk,
                               'type': transaction.transaction_type,
                               'category': transaction.category.name,
                               'date': transaction.date,
                               'amount': transaction.amount,
                               'comment': transaction.comment,
                               }
                return JsonResponse(context)
            except KeyError as e:
                print e
                print "KeyError in GET in new_transaction"
        else:
            raise Http404(request)
    else:
        print 'new_transaction not ajax'
        raise Http404(request)


@csrf_exempt
def update_delete_transaction(request, pk):
    if request.is_ajax():
        if request.method == 'POST':
            try:
                t_id = request.POST['id']
                t_type = request.POST['type']
                cat = request.POST['category']
                sub = request.POST['subcategory']
                date = request.POST['date']
                comment = request.POST['comment']
                amount = request.POST['amount']
                category = Category.objects.get(name=cat)
                subcategory = Subcategory.objects.get(name=sub)
                account_id = request.POST['idAccount']
                account = get_object_or_404(Account, pk=account_id)
                transaction = Transaction.objects.get(pk=t_id)

                if t_type == 'i':
                    account.balance += Decimal(float(amount))
                else:
                    account.balance -= Decimal(float(amount))
                account.save()
                transaction.transaction_type = t_type
                transaction.category = category
                transaction.subcategory = subcategory
                transaction.comment = comment
                transaction.date = date
                transaction.save()

                return JsonResponse({'code': '200',
                                     'msg': 'transaction added'})

            except KeyError as e:
                print e.args
                print "KeyError at update_delete_transaction POST"

        if request.method == 'GET':
            try:
                transaction_id = request.GET['id']
                transaction = Transaction.objects.get(pk=transaction_id)

                amount = transaction.amount

                account = Account.objects.get(transaction=transaction)
                if transaction.transaction_type == 'i':
                    account.balance -= amount
                else:
                    account.balance += amount
                account.save()

                transaction.delete()

                return JsonResponse({'code': '200',
                                     'msg': 'transaction deleted',
                                     'id': transaction_id})

            except KeyError as e:
                print e.args
                print "KeyError at update_delete_transaction GET"
                raise HttpResponseServerError(request)

        else:
            print "update_delete_transaction request.method not supported"
            raise Http404(request)
    else:
        print "update_delete_transaction not ajax"
        raise Http404(request)


@csrf_exempt
def cats_subs(request):
    json_response = Category.to_dict()
    return JsonResponse(json_response)


@csrf_exempt
def new_del_sub(request):
    if request.is_ajax():
        if request.method == 'POST':
            try:
                cat = request.POST['category']
                name = request.POST['subcategory']
                category = get_object_or_404(Category, name=cat)
                subcategory = Subcategory(name=name, category=category)
                subcategory.save()

                return JsonResponse({'code': '200',
                                     'msg': 'ok'})

            except KeyError as e:
                print "KeyError new_del_sub POST"
                print e.args
                return HttpResponseServerError(request)
        else:
            try:
                sub_id = request.GET['id']
                sub = get_object_or_404(Subcategory, pk=sub_id)
                sub.delete()
                return JsonResponse({'code': '200',
                                     'msg': 'deleted'})

gvi/transactions/templates/transactions/balance_detail.html
<!-- dashboard -->

{% extends "base_generic.html" %}

{% block menubar %}

{% endblock %}

{% block content %}
    <div class="row col-xs-offset-1">
        <!-- Hub info -->
        <div class="row">
            <div class="col-xs-12">
                <h1>
                    <div id="hubname">Balance Details</div>
                </h1>
                <h4>
                    <div id="hubinfo">
                        <ul class="list-unstyled">
                            {% if a.account_type == 'b' %}
                                <li>Currency: {{ a.currency }}</li>
                                <li>Bank: {{ a.bank_name }}</li>
                                <li>Account No. {{ a.number }}</li>
                            {% else %}
                                <li>Currency: {{ a.currency }}</li>
                            {% endif %}

                            <li>Initial Budget: $15,000</li>
                            <li>Remaining Budget: $10,000</li>
                            <li>Total Expenses: $5,000</li>
                        </ul>
                    </div>
                </h4>

            </div>
        </div>
        <!-- /.row Hub info -->

        <!-- Form data to backend -->
        <form action="{% url 'transactions:search_transactions' %}" method="post">
            {% csrf_token %}

            <!-- Category title -->
            <div class="row">
                <div class="col-xs-8">
                    <div class="col-xs-1">
                        <label class="select-title">Enable</label>
                    </div>
                    <div class="col-xs-1">
                        <label class="select-title">Category</label>
                    </div>
                </div>
            </div>
            <!-- /.row Category/Subcategory title -->

            <!-- Category -->
            <div class="row">
                <div class="col-xs-8">
                    <div class="col-xs-1 checkbox">
                        <div class="pull-right">
                            <label class="select-title">
                                <input type="checkbox" id="enableCategory" name="enableCategory">
                            </label>
                        </div>
                    </div>
                    <div class="col-xs-11 pull-left">
                        <div class="form-group">
                            <select class="form-control" id="categorySelect" name="categorySelect">
                                {% for a in category %}
                                    <option>{{ a.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.row Category -->

            <!-- Subcategory title -->
            <div class="row">
                <div class="col-xs-8">
                    <div class="col-xs-1 col-xs-offset-1">
                        <label class="select-title">Subcategory</label>
                    </div>
                </div>
            </div>
            <!-- /.row Subcategory title -->

            <!-- Subcategory -->
            <div class="row">
                <div class="col-xs-8">
                    <div class="col-xs-1 checkbox">
                        <div class="pull-right">
                            <label class="select-title">
                                <input type="checkbox" name="enableSubcategory" id="enableSubcategory">
                            </label>
                        </div>
                    </div>
                    <div class="col-xs-11 pull-left">
                        <div class="form-group">
                            <select class="form-control" id="subcategorySelect" name="subcategorySelect">
                                {% for a in subcategory %}
                                    <option>{{ a.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <!-- /.col-xs-4 -->
                </div>
            </div>
            <!-- /.row Subcategory -->
            <div class="row">
                <div class="col-xs-8">
                    <div class="alert alert-danger" role="alert" id="dateError" name="dateError" hidden="true">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <strong>Error:</strong> Initial date is greater than end date.
                    </div>
                </div>
            </div>

            <!-- To - From title -->
            <div class="row">
                <div class="col-xs-8">
                    <div class="col-xs-1">
                        <label class="select-title">From</label>
                    </div>
                    <div class="col-xs-1 col-xs-offset-7">
                        <div class="pull-left">
                            <label class="select-title">To</label>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.row To - From title -->

            <!-- Date data and search button -->
            <div class="row">
                <div class="col-xs-8">
                    <div class="col-xs-4">
                        <div class="form-group">
                            <div class='input-group date' id='datetimepickerFrom'>
                                <input type='text' class="form-control" id="fromDate" name="fromDate" readonly/>
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                 </span>
                            </div>
                        </div>
                    </div>


                    <div class="col-xs-4">
                        <hr class="horizontal-separator">
                    </div>

                    <div class="col-xs-4">
                        <div class="form-group">
                            <div class='input-group date' id='datetimepickerTo'>
                                <input type='text' class="form-control" id="toDate" name="toDate" readonly/>
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                 </span>
                            </div>
                        </div>
                    </div>

                </div>
                <button type="submit" class="btn btn-info pull-left">
                    <span class="glyphicon glyphicon-search" aria-hidden="true"></span> search
                </button>
            </div>
            <!-- /.row Date data and search button -->
        </form>
        <!-- Form data to backend -->

        <!-- Transaction table -->
        <div class="row">
            <div class="col-xs-8">
                <p class="tableTitle">Bank Accounts:</p>
                <table class="table table-hover">
                    <tr>
                        <th>Date</th>
                        <th>Code</th>
                        <th>Category</th>
                        <th>Subcategory</th>
                        <th>Comment</th>
                        <th>Amount</th>
                        <th>Balance</th>
                        <th>Edit</th>
                    </tr>

                    <!-- For to fill info about each account -->
                    {% for a in transactions %}
                        <tr>
                            <td>{{ a.date }}</td>
                            <td>{{ a.category.number }}</td>
                            <td>{{ a.category.name }}</td>
                            <td>{{ a.subcategory.name }}</td>
                            <td>{{ a.comment }}</td>
                            <td>{{ a.amount }}</td>
                            <td>{{ a.balance }}</td>
                            <td><a class="glyphicon glyphicon-pencil" data-toggle="modal"
                                   data-target="#modalEditTransaction" onclick="editTransaction()"></a></td>
                        </tr>
                    {% endfor %}
                    <!-- ****************************************-->

                </table>
            </div>
        </div><!-- /.row Transaction table -->

    </div>
{% endblock %}

gvi/transactions/templates/transactions/dashboard.html
<!-- dashboard -->

{% extends "base_generic.html" %}

{% block menubar %}
<!-- Menu bar options: Add account, Money transfer and Currencies -->
<p class="navbar-text"><a href="{%url 'transactions:subcategories'%}" style="color: #ffffff; text-decoration: none; font-weight: 500; font-size: 12px;"><button class="btn btn-default btn-sm glyphicon glyphicon-menu-right" type="button" id="btnCurrencies">  Subcategories</button></a></p>
{% endblock %}

{% block content %}

<!-- Info about money left and expenses-->
<div class="row">
    <div class="col-md-5 col-md-offset-1">
        <h1>Money left</h1><br>
        <ul class="list-unstyled">

            <!-- For to display all currencies and how much money they have -->
            {% for c in currencies %}
            <li class="text">{{ c }}: ${{ c.total }}</li>
            {% endfor %}
            <!-- **********************************************************-->

        </ul>
    </div>
    <div class="col-md-5">
        <h1>Expenses</h1><br>
        <ul class="list-unstyled">

            <!-- For to display currencies and their total expenses -->
            {% for c in currencies %}
            <li class="text">{{ c }}: ${{ c.expenses }}</li>
            {% endfor %}
            <!--*****************************************************-->

        </ul>
    </div>
</div><br>
<!-- Ends info about money left and expenses -->

<!-- Table for bank accounts -->
<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <p class="tableTitle">Bank Accounts:</p>
        <table class="table table-hover" id="bankAccounts">
            <tr>

                <th>Currency</th>
                <th>Amount</th>
                <th>Bank</th>
                <th>Account #</th>
                <th style="padding-top: 0px; padding-bottom: 0px;">Balance<br>Details</th>
            </tr>

            <!-- For to fill info about each account -->
            {% for a in bank_acc %}

            <tr id="{{ a.id }}">
                <td hidden id="pk">{{ a.id }}</td>
                <td>{{ a.currency }}</td>
                <td>{{ a.balance }}</td>
                <td>{{ a.bank_name }}</td>
                <td>{{ a.number }}</td>
                <td><a class="glyphicon glyphicon-list-alt" id="btnDetails" href="{% url 'transactions:balance_detail' a.id %}"></a></td>
            </tr>
            {% endfor %}
            <!-- ****************************************-->

        </table>
    </div>
</div>
<!-- Ends table for bank accounts-->

<!-- Table for cash accounts -->
<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <p class="tableTitle">Cash Accounts:</p>
        <table class="table table-hover" id="cashAccounts">
            <tr>

                <th>Currency</th>
                <th>Amount</th>
                <th style="padding-top: 0px; padding-bottom: 0px;">Balance<br>Details</th>
            </tr>

            <!-- For to fill information about each account-->
            {% for a in cash_acc %}

            <tr id="{{ a.id }}">
                <td hidden id="pk">{{ a.id }}</td>


                <td>{{ a.currency }}</td>
                <td>{{ a.balance }}</td>
                <td><a class="glyphicon glyphicon-list-alt" id="btnDetails" href="{% url 'transactions:balance_detail' a.id %}"></a></td>
            </tr>
            {% endfor %}
            <!--***********************************************-->

        </table>
    </div>
</div>
<!-- Ends table for cash accounts -->

{% endblock %}

gvi/transactions/templates/transactions/subcategories.html
{% extends 'base_generic.html' %}

{% block menubar %}
<!-- Menu bar options: Accounts and Add Currency-->
    <p class="navbar-text"><a href="{% url 'transactions:index' %}" style="color: black; text-decoration: none;"> <button class="btn btn-default btn-sm glyphicon glyphicon-menu-left" type="button" id="btnAccounts"> Accounts</button></a></p>
{% endblock %}

{% block content %}
<!-- Title -->
<div class="row">
    <div class="col-md-5 col-md-offset-1" style="padding-bottom: 50px;">
        <h1>Subcategories</h1>
    </div>

</div>

<!-- Currencies table-->
<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <table class="table table-hover" id="bankAccounts">
            <tr>
                <th>Subcategory</th>
                <th>Delete</th>
            </tr>

            <!-- For to fill info about each currency -->
            {% for c in subs %}
            <tr id="{{ c.id }}.{{ c.name }}">
                <td hidden id="pk">{{ c.id }}</td>
                <td>{{ c.name }}</td>

                <!-- Delete button-->
                <td><button class="glyphicon glyphicon-remove" id="btnDeleteSubs" data-toggle="modal" data-target="#modalDeleteSubs" onclick="currencyDeleteConfirmSubs($(this).closest('tr'))"></button></td>
            </tr>
            {% endfor %}
            <!-- **************************************-->

        </table>
    </div>
</div>
<!-- End of currencies table-->

<!--Delete Currency Modal-->
<div class="modal fade modalStyles" id="modalDeleteSubs" tabindex="-1" role="dialog" aria-labelledby="labelDeleteSubs">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">

            <!-- Header-->
            <div class="modal-header">
                <h2 class="modal-title modalHeader" id="labelDeleteSubs">Delete Subcategory</h2>
            </div>
            <!-- Ends header -->

            <!-- Body -->
            <div class="modal-body">
                <div class="container-fluid">
                    <br>
                    <!-- Question -->
                    <div class="row">
                        <label id="labelSubsName"></label>
                    </div>

                    <!-- Currency id-->
                    <div>
                        <input type="hidden" id="subId">
                    </div>
                </div>
            </div>
            <!-- Ends body -->

            <!-- Footer -->
            <div class="modal-footer">
                <!-- Yes and No buttons-->
                <button type="button" class="btn btn-sm col-sm-2 col-md-offset-4" id="subDeleteYes" onmouseover="deleteBtnOverYes($(this))" onmouseout="deleteBtnOutYes($(this))">Yes</button>
                <button type="button" class="btn btn-sm col-sm-2" id="subDeleteNo" data-dismiss="modal" onmouseover="deleteBtnOverNo($(this))" onmouseout="deleteBtnOutNo($(this))">No</button>
            </div>
            <!-- Ends footer -->
        </div>
    </div>
</div>
<!-- Ends Delete Currency Modal-->

{% endblock %}