gvi/budgets/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^variable/$', views.variable, name='variable'),
    url(r'^create_budget/$', views.create_budget, name='create_budget'),
    url(r'^create_budget_variable/$', views.create_budget_variable, name='create_budget_variable'),
    url(r'^search_budget$', views.search_budget, name='search_budget'),
    url(r'^variable/search_budget_variable$', views.search_budget_variable, name='search_budget_variable'),
]

gvi/gvi/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^reports/', include('reports.urls', namespace='reports', app_name='reports')),
    url(r'^budgets/', include('budgets.urls', namespace='budgets', app_name='budgets')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts', app_name='accounts')),
    url(r'^transactions/', include('transactions.urls', namespace='transactions', app_name='transactions')),
    url(r'^hubs/', include('hubs.urls', namespace='hubs', app_name='hubs')),
    url(r'^users/', include('users_m.urls', namespace='users_m', app_name='users_m')),
    url(r'^admin/', include(admin.site.urls)),
]

gvi/budgets/models.py
from django.db import models

class Budget(models.Model):
    number = models.CharField(max_length=100, unique=True)
    initial_date = models.DateTimeField()
    final_date = models.DateTimeField(blank=True)
    hub = models.ForeignKey('hubs.Hubs')

    def __str__(self):
        return self.number

class BudgetElement(models.Model):
    FIXED = 'f'
    VARIABLE = 'v'
    TYPE_CHOICES = (
            (FIXED, 'Fixed'),
            (VARIABLE, 'Variable'),
    )
    budget_type = models.CharField(max_length=5, choices=TYPE_CHOICES, default=FIXED)
    amount = models.DecimalField(decimal_places=2, max_digits=19, default=0)
    number = models.ForeignKey(Budget)
    currency = models.ForeignKey('accounts.Currency')
    category = models.ForeignKey('transactions.Category')
    #subcategory = models.ForeignKey('transactions.Subcategory', blank=True)
    
    """
    If the element is variable
    """
    FIRST_W = 'f'
    OTHER_W = 'o'
    V_TYPE_CHOICES = (
            (FIRST_W, 'First Week'),
            (OTHER_W, 'Other Week'),
    )
    variable_type = models.CharField(max_length=5, choices=V_TYPE_CHOICES, default=OTHER_W)

    def __str__(self):
        return str(self.amount)+":" + self.number.number

gvi/transactions/models.py
from django.db import models
from django.utils import timezone


class Category(models.Model):
    name = models.CharField(max_length=50)
    number = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return str(self.name) + ":" + str(self.number)

    def subs(self):
        sub_list = []
        ss = Subcategory.objects.filter(category=self)
        for s in ss:
            sub_list.append(s.name)
        return sub_list

    @classmethod
    def to_dict(cls):
        cats = cls.objects.all()
        le_dict = {}
        for cat in cats:
            le_dict[cat.name] = cat.subs()
        return le_dict


class Subcategory(models.Model):
    name = models.CharField(max_length=50)
    category = models.ForeignKey(Category)

    def __str__(self):
        return self.name


class Transaction(models.Model):
    IN = 'i'
    OUT = 'o'
    TYPE_CHOICES = (
        (IN, 'Money In'),
        (OUT, 'Money Out'),
    )
    transaction_type = models.CharField(max_length=5, choices=TYPE_CHOICES, default=OUT)
    category = models.ForeignKey(Category, blank=True, null=True)
    date = models.DateField()
    subcategory = models.ForeignKey(Subcategory, blank=True, null=True)
    comment = models.CharField(max_length=200, blank=True)
    amount = models.DecimalField(decimal_places=2, max_digits=19)
    balance = models.DecimalField(decimal_places=2, max_digits=19)
    account = models.ForeignKey('accounts.Account')

    def __str__(self):

        return self.transaction_type + str(self.amount)

    @classmethod
    def first_year(cls):
        years = cls.objects.order_by('date')[0].date.year
        return years

    @classmethod
    def year_range(cls):
        year_range = [cls.first_year()]

        if timezone.now().year == year_range[-1]:
            return year_range
        else:
            while year_range[-1] != timezone.now().year:
                year_range.append(year_range[-1] + 1)
            return year_range

        return 'Critical Error'

gvi/budgets/forms.py
from django import forms


    
class BudgetForm(forms.Form):
    category = forms.CharField()
    amount = forms.CharField()
    currency = forms.CharField()

gvi/budgets/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.forms.formsets import formset_factory

from .models import BudgetElement, Budget
from accounts.models import Currency, Account
from transactions.models import Transaction, Category, Subcategory
from hubs.models import Hubs

import hashlib
import time
import datetime


#{{{Index
def index(request):
    category = Category.objects.all()
    currency = Currency.objects.all() 
    
    context = {'category': category,
            'currency':currency,
            }
    
    return render(request, 'budgets/dashboard.html', context)
#}}}

#{{{Variable
def variable(request):
    category = Category.objects.all()
    currency = Currency.objects.all()

    context = {'category': category,
            'currency':currency,
            }

    return render(request, 'budgets/variable.html', context)
#}}}

#{{{Create Budget
def create_budget(request):

    print "******* FOR ***"
    print request.body
    AMOUNT = 0
    CATEGORY = 1
    CURRENCY = 2

    form_elements = []
    counter = 0
    
    hash = hashlib.sha1()
    hash.update(str(datetime.datetime.now()))
    BUDGET_NUMBER = hash.hexdigest()

    hub = Hubs.objects.all()[0]
    
    new_budget = Budget(number=BUDGET_NUMBER,
                        initial_date=request.POST['newBudgetFromDate'],
                        final_date=request.POST['newBudgetToDate'],
                        hub=hub)
    
    new_budget.save()

    for key in request.POST:
        if "form" in key:
            form_elements.append(key)
            print key + ':' + request.POST[key]
    
    print len(form_elements)
    
    sort_form_elements = sorted(form_elements)
     
    while counter < len(form_elements):
        print sort_form_elements[counter]
        category = Category.objects.filter(name=request.POST[sort_form_elements[counter+CATEGORY]])[0]
        currency = Currency.objects.filter(contraction=request.POST[sort_form_elements[counter+CURRENCY]])[0]
        new_budget_element = BudgetElement(amount=request.POST[sort_form_elements[counter+AMOUNT]],
                                           category=category,
                                           currency=currency,
                                           number=new_budget,
                                           budget_type='f')
        new_budget_element.save()
        counter += 3
    

    print "******* END ***"
   


    category = Category.objects.all()
    currency = Currency.objects.all()

    context = {'category': category,
            'currency':currency,
            }   

    return render(request, 'budgets/dashboard.html', context)
#}}}

#{{{Create_budget_variable
def create_budget_variable(request):

    print "******* FOR ***"
    print request.body
    AMOUNT = 0
    CATEGORY = 1
    CURRENCY = 2
    VARIABLE_TYPE = 3

    form_elements = []
    counter = 0

    hash = hashlib.sha1()
    hash.update(str(datetime.datetime.now()))
    BUDGET_NUMBER = hash.hexdigest()

    hub = Hubs.objects.all()[0]
    
    new_budget = Budget(number=BUDGET_NUMBER,
                        initial_date=request.POST['newBudgetFromDate'],
                        final_date=request.POST['newBudgetToDate'],
                        hub=hub)
    
    new_budget.save()

    for key in request.POST:
        if "form" in key:
            form_elements.append(key)
            print key + ':' + request.POST[key]
    
    print len(form_elements)
    
    sort_form_elements = sorted(form_elements)
     
    while counter < len(form_elements):
        print sort_form_elements[counter]
        category = Category.objects.filter(name=request.POST[sort_form_elements[counter+CATEGORY]])[0]
        currency = Currency.objects.filter(contraction=request.POST[sort_form_elements[counter+CURRENCY]])[0]
        #flag_type = request.POST.get(sort_form_elements[counter+VARIABLE_TYPE])
        try:
            if "type" in sort_form_elements[counter+VARIABLE_TYPE]:
                print "estoy en verdad"
                variable_type = 'f'
                variable_off = 4
            else:
                print "estoy en no"
                variable_type = 'o'
                variable_off = 3
        except:
            variable_off = 3
            variable_type = 'o'

        new_budget_element = BudgetElement(amount=request.POST[sort_form_elements[counter+AMOUNT]],
                                           category=category,
                                           currency=currency,
                                           number=new_budget,
                                           budget_type='v',
                                           variable_type=variable_type)
        new_budget_element.save()
        
        counter += variable_off
            

    print "******* END ***"
   


    category = Category.objects.all()
    currency = Currency.objects.all()

    context = {'category': category,
            'currency':currency,
            }

    return render(request, 'budgets/variable.html', context)
#}}}

#{{{Search_budget
def search_budget(request):
    
    total_category = {}
    total_subcategory = {}

    category = Category.objects.all()
    hub = Hubs.objects.all()[0]
    transactions = Transaction.objects.filter(account__owner__name=hub.name)
    transactions = transactions.filter(date__range=[fromDate, toDate])
    accounts = Account.objects.filter(owner=hub)
    currency = Currency.objects.filter(account=accounts)
    category = Category.objects.filter(transaction=transactions)
    subcategory = Subcategory.objects.filter(transaction=transactions)


    for i in currency:
        transactions_curr = transactions.filter(account__currency__contraction=i.contraction)
        for x in category:
            transactions_curr_cat = transactions_curr.filter(category=x)
            sub_cat = subcategory.filter(category__name=x.name)
            for y in sub_cat:
                transactions_curr_cat_sub = transactions_curr_cat.filter(subcategory=x)
                for z in transactions_curr_cat_sub: 
                    total_category[i.contracction+x.name] += z.amount
                    total_subcategory[i.contraction+y.name] += z.amount


    print total_category
    print total_subcategory
    context = {'category': category,
            'currency':currency,
            }

    return render(request, 'budgets/dashboard.html', context)
#}}}

#{{{Search_budget_variable 
def search_budget_variable(request):
    print "**********"
    print request.body
    print "**********"

    total_category = 0
    total_subcategory = 0
    search_json = {}
    category_jason = {}
    sub_jason = {}
    fromDate = request.POST.get('fromDate')
    toDate = request.POST.get('toDate')
    
    category = Category.objects.all()
    hub = Hubs.objects.all()[0]
    transactions = Transaction.objects.filter(account__owner__name=hub.name)
    transactions = transactions.filter(date__range=[fromDate, toDate])
    accounts = Account.objects.filter(owner=hub)
    currency = Currency.objects.filter(account=accounts)
    category_transaction = Category.objects.filter(transaction=transactions)
    subcategory = Subcategory.objects.filter(transaction=transactions)


    for i in currency:
        transactions_curr = transactions.filter(account__currency__contraction=i.contraction)  
        
        for x in category_transaction:
            transactions_curr_cat = transactions_curr.filter(category=x)
            sub_cat = subcategory.filter(category__name=x.name)
            sub_jason["total"] = 0
            for y in sub_cat:
                transactions_curr_cat_sub = transactions_curr_cat.filter(subcategory=y)
                 
                for z in transactions_curr_cat_sub: 
                    
                    try:
                        sub_jason[y.name] += z.amount
                        sub_jason["total"] += z.amount
                        #total_category[i.contraction+x.name] += z.amount
                        #total_subcategory[i.contraction+y.name] += z.amount
                    
                    except:
                        sub_jason[y.name] = z.amount
                        sub_jason["total"] += z.amount
                        #total_subcategory[i.contraction+y.name] = z.amount
                        #total_category[i.contraction+x.name] = z.amount
                
                category_jason[x.name] = sub_jason
            search_json[i.name] = category_jason

    
    print search_json
    print category
    print category_transaction
    print total_category
    print total_subcategory
 
    context = {'category': category,
            'category_transaction':category_transaction,
            'currency':currency,
            'subcategory':subcategory,
            'total_category':total_category,
            'total_subcategory':total_subcategory,
            }

    return render(request, 'budgets/dashboard.html', context)
#}}}

gvi/budgets/templates/budgets/dashboard.html
<!-- dashboard -->

{% extends "base_generic.html" %}

{% block menubar %}

{% endblock %}

{% block content %}
    <div class="row col-xs-11">
        <div class="row" id="hubname">
            <h1>
                <div class="budgets">Budgets</div>
            </h1>
        </div>


        <div class="col-xs-6" id="leftBudget">
            <form action="{% url 'budgets:create_budget' %}" method="post">
                {% csrf_token %}

                <div class="row">
                    <div class="col-xs-6">
                        <button class="btn btn-info add_field_button add-spacing">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add new
                        </button>

                    </div>
                    <div class="col-xs-6">
                        <button class="btn btn-success pull-right" type="submit" name="budgetSave" id="budgetSave">
                            <span class="glyphicon glyphicon-floppy-save" aria-hidden="true"></span> Save
                        </button>

                    </div>

                </div>
                <div class="row">
                    <div class="col-xs-12">
                        <div class="alert alert-danger" role="alert" id="dateError" name="dateError" hidden="true">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <strong>Error:</strong> Initial date is greater than end date.
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-xs-5">
                        <div class="form-group">
                            <div class='input-group date datepick'>
                                <input type='text' class="form-control" id="newBudgetFromDate" name="newBudgetFromDate" readonly/>
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                 </span>
                            </div>
                        </div>
                    </div>


                    <div class="col-xs-2">
                        <hr class="horizontal-separator">
                    </div>

                    <div class="col-xs-5">
                        <div class="form-group">
                            <div class='input-group date datepick'>
                                <input type='text' class="form-control" id="newBudgetToDate" name="newBudgetToDate" readonly/>
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                 </span>
                            </div>
                        </div>
                    </div>

                </div>

                <div class="input_fields_wrap">
                    <div class="row add-spacing">

                        <div class="col-xs-5">
                            <select class="form-control" id="form-0-category" name="form-0-category">
                                {% for a in category %}
                                    <option>{{ a.name }}</option>
                                {% endfor %}
                            </select>

                        </div>
                        <div class="col-xs-3">
                            <input type="number" id="form-0-amount" name="form-0-amount" class="form-control amount-offset" placeholder="Amount" required>
                        </div>
                        <div class="col-xs-3">
                            <select class="form-control currency-offset" name="form-0-currency" id="form-0-currency">
                                {% for a in currency %}
                                    <option>{{ a.contraction }}</option>
                                {% endfor %}
                            </select>

                        </div>
                    </div>

                </div>

            </form>
        </div>
        <div class="col-xs-6" id="rightBudget">
            <form action="{% url 'budgets:search_budget_variable' %}" method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col-xs-5">
                        <div class="form-group">
                            <div class='input-group date datepick'>
                                <input type='text' class="form-control" id="fromDate" name="fromDate" readonly/>
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                 </span>
                            </div>
                        </div>
                    </div>


                    <div class="col-xs-2">
                        <hr class="horizontal-separator">
                    </div>

                    <div class="col-xs-5">
                        <div class="form-group">
                            <div class='input-group date datepick'>
                                <input type='text' class="form-control" id="toDate" name="toDate" readonly/>
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                 </span>
                            </div>
                        </div>
                    </div>

                </div>
                <div class="row">
                    <div class="col-xs-6">
                        <button type="submit" class="btn btn-info pull-left">
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span> search
                        </button>
                    </div>
                </div>
            </form>

            <div class="budgets budgets_wrap">
                {% for a in currency %}
                    <div class="row">
                        <h3>{{ a.name }}</h3>
                    </div>
                    {% for b in category %}
                        <div class="row">
                            <div class="col-xs-8">
                                <h4>{{ b.name }} amount spent: <label> 5400</label></h4>
                            </div>

                            <div class="col-xs-4">
                                <div class="col-xs-1 checkbox">
                                    <a href="#" class="toggle_sub" name="{{ a.id }}{{ b.number }}">
                                        <span class="glyphicon glyphicon-triangle-bottom"></span>
                                    </a>

                                </div>
                            </div>
                        </div>
                        {% for c in b.subcategory_set.all %}
                            <div class="row">
                                <div class="col-xs-12">
                                    <ul name="{{ a.id }}{{ b.number }}sub" id="{{ a.id }}{{ b.number }}sub" class="toggle_sub">
                                        <li><h5>{{ c.name }}: <label> 5400</label></h5></li>
                                    </ul>
                                </div>
                            </div>
                        {% endfor %}

                    {% endfor %}
                {% endfor %}
            </div>

        </div>




    </div>



{% endblock %}

gvi/budgets/templates/budgets/variable.html
<!-- dashboard -->

{% extends "base_generic.html" %}

{% block menubar %}

{% endblock %}

{% block content %}
    <div class="row col-xs-11">
        <div class="row" id="hubname">
            <h1>
                <div class="budgets">Budgets</div>
            </h1>
        </div>


        <div class="col-xs-6" id="leftBudget">
            <form action="{% url 'budgets:create_budget_variable' %}" method="post">
                {% csrf_token %}

                <div class="row">
                    <div class="col-xs-6">
                        <button class="btn btn-info add_field_button_variable add-spacing">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add new
                        </button>

                    </div>
                    <div class="col-xs-6">
                        <button class="btn btn-success pull-right" type="submit" name="budgetSave" id="budgetSave">
                            <span class="glyphicon glyphicon-floppy-save" aria-hidden="true"></span> Save
                        </button>

                    </div>

                </div>
                <div class="row">
                    <div class="col-xs-12">
                        <div class="alert alert-danger" role="alert" id="dateError" name="dateError" hidden="true">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <strong>Error:</strong> Initial date is greater than end date.
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-xs-5">
                        <div class="form-group">
                            <div class='input-group date datepick'>
                                <input type='text' class="form-control" id="newBudgetFromDate" name="newBudgetFromDate" readonly/>
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                 </span>
                            </div>
                        </div>
                    </div>


                    <div class="col-xs-2">
                        <hr class="horizontal-separator">
                    </div>

                    <div class="col-xs-5">
                        <div class="form-group">
                            <div class='input-group date datepick'>
                                <input type='text' class="form-control" id="newBudgetToDate" name="newBudgetToDate" readonly/>
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                 </span>
                            </div>
                        </div>
                    </div>

                </div>
                <div class="row">
                    <div class="col-xs-offset-8 col-xs-4">
                        <label class=" checkbox-label-offset">First Week</label>
                    </div>
                </div>

                <div class="input_fields_wrap">
                    <div class="row add-spacing">

                        <div class="col-xs-4">
                            <select class="form-control" id="form-0-category" name="form-0-category">
                                {% for a in category %}
                                    <option>{{ a.name }}</option>
                                {% endfor %}
                            </select>

                        </div>
                        <div class="col-xs-3">
                            <input type="number" id="form-0-amount" name="form-0-amount" class="form-control amount-offset" placeholder="Amount" required>
                        </div>
                        <div class="col-xs-3">
                            <select class="form-control currency-offset" name="form-0-currency" id="form-0-currency">
                                {% for a in currency %}
                                    <option>{{ a.contraction }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="col-xs-1">
                            <div class="checkbox checkbox-offset">
                                <input type="checkbox" name="form-0-type" id="form-0-type" value="false">
                            </div>
                        </div>
                    </div>
                </div>

            </form>
        </div>
        <div class="col-xs-6" id="rightBudget">
            <form action="{% url 'budgets:search_budget_variable' %}" method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col-xs-5">
                        <div class="form-group">
                            <div class='input-group date datepick'>
                                <input type='text' class="form-control" id="fromDate" name="fromDate" readonly/>
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                 </span>
                            </div>
                        </div>
                    </div>


                    <div class="col-xs-2">
                        <hr class="horizontal-separator">
                    </div>

                    <div class="col-xs-5">
                        <div class="form-group">
                            <div class='input-group date datepick'>
                                <input type='text' class="form-control" id="toDate" name="toDate" readonly/>
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                 </span>
                            </div>
                        </div>
                    </div>

                </div>

                <div class="row">
                    <div class="col-xs-6">
                        <button type="submit" class="btn btn-info pull-left">
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span> search
                        </button>
                    </div>
                </div>
            </form>

            <div class="budgets budgets_wrap">
                {% for a in currency %}
                    <div class="row">
                        <h3>{{ a.name }}</h3>
                    </div>
                    {% for b in category %}
                        <div class="row">
                            <div class="col-xs-8">
                                <h4>{{ b.name }} amount spent: <label> 5400</label></h4>
                            </div>

                            <div class="col-xs-4">
                                <div class="col-xs-1 checkbox">
                                    <a href="#" class="toggle_sub" name="{{ a.id }}{{ b.number }}">
                                        <span class="glyphicon glyphicon-triangle-bottom"></span>
                                    </a>

                                </div>
                            </div>
                        </div>
                        {% for c in b.subcategory_set.all %}
                            <div class="row">
                                <div class="col-xs-12">
                                    <ul name="{{ a.id }}{{ b.number }}sub" id="{{ a.id }}{{ b.number }}sub" class="toggle_sub">
                                        <li><h5>{{ c.name }}: <label> 5400</label></h5></li>
                                    </ul>
                                </div>
                            </div>
                        {% endfor %}

                    {% endfor %}
                {% endfor %}
            </div>

        </div>




    </div>



{% endblock %}