gvi/gvi/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^reports/', include('reports.urls', namespace='reports', app_name='reports')),
    url(r'^budgets/', include('budgets.urls', namespace='budgets', app_name='budgets')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts', app_name='accounts')),
    url(r'^transactions/', include('transactions.urls', namespace='transactions', app_name='transactions')),
    url(r'^hubs/', include('hubs.urls', namespace='hubs', app_name='hubs')),
    url(r'^users/', include('users_m.urls', namespace='users_m', app_name='users_m')),
    url(r'^admin/', include(admin.site.urls)),
]

gvi/hubs/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^hub/search/$', views.hub_search, name='hub_search'),
    url(r'^hub/$', views.add_get_hub, name='hub'),
    url(r'^hub/(?P<pk>\d+)/$', views.hub_detail, name='hub_detail'),
    url(r'^hub/(?P<pk>\d+)/create_account/$', views.hub_add_account, name='hub_add_account'),
    url(r'^hub/(?P<pk>\d+)/change_account/$', views.hub_account_update_delete, name='hub_update_account'),
    url(r'^change_hub/$', views.hub_update_delete, name='hub_update_delete'),
    url(r'^hub/account/(?P<pk>\d+)/$', views.account_detail, name='account_detail'),
]

gvi/transactions/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^search_transactions/$', views.search_transactions, name='search_transactions'),
    url(r'^transaction/account/(?P<pk>\d+)/$', views.balance_detail, name='balance_detail'),
    url(r'^transaction/account/(?P<pk>\d+)/new_transaction/$', views.new_transaction, name='new_transaction'),
    url(r'^transaction/account/(?P<pk>\d+)/change_transaction/$', views.update_delete_transaction,
        name='change_transaction'),
    url(r'^cats_subs/$', views.cats_subs, name='cats_subs'),
    url(r'^new_subcategory/$', views.new_del_sub, name='change_sub'),
    url(r'^subcategories/$', views.subcategories, name='subcategories'),
]

gvi/hubs/models.py
from django.db import models

from accounts.models import Account


class Hubs(models.Model):
    HUB = 'h'
    C_MANAGER = 'c'
    TYPE_CHOICES = (
        (HUB, 'Hub'),
        (C_MANAGER, 'Country Manager'),
    )
    hub_type = models.CharField(max_length=5, choices=TYPE_CHOICES, default=HUB)
    name = models.CharField(max_length=100)
    manager = models.CharField(max_length=100)
    country = models.CharField(max_length=50)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    def bank_accounts(self):
        accounts = Account.objects.filter(owner=self).filter(account_type='b')
        return accounts

    def cash_accounts(self):
        accounts = Account.objects.filter(owner=self).filter(account_type='c')
        return accounts

    def expenses(self):
        pass

    def money_left(self):
        pass

gvi/hubs/views.py
from django.shortcuts import render, get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse, HttpResponseServerError
from django.http import HttpResponse, Http404

from .models import Hubs
from accounts.models import Currency, Account
from transactions.models import Category, Subcategory


def index(request):
    hubs = Hubs.objects.all()
    context = {'hubs': hubs}
    return render(request, 'hubs/dashboard.html', context)


@csrf_exempt
def add_get_hub(request):
    if request.is_ajax():
        if request.method == 'POST':
            try:
                name = request.POST['name']
                manager = request.POST['manager']
                country = request.POST['country']
                hub = Hubs(name=name, manager=manager, country=country)
                hub.save()
            except (KeyError, Exception) as e:
                print "KeyError / Exception in POST add_delete_hub"
                print e.args
                return HttpResponseServerError(request)

            return JsonResponse({'code': '200',
                                 'msg': 'all ok',
                                 })
        else:
            try:
                hub_id = request.GET['id']
                hub = get_object_or_404(Hubs, pk=hub_id)
                json_hub = {'id': hub.pk,
                            'name': hub.name,
                            'manager': hub.manager,
                            'country': hub.country,
                            }

            except KeyError as e:
                print e.args
                print "GET add_delete_hub"
                return HttpResponseServerError(request)

            return JsonResponse(json_hub)

    else:
        raise Http404("Not Found")


@csrf_exempt
def hub_update_delete(request):
    if request.is_ajax():
        if request.method == 'POST':
            try:
                print "*******"
                print request.body
                print "*******"
                hub_id = request.POST['id']
                name = request.POST['name']
                country = request.POST['country']
                manager = request.POST['manager']
                hub = get_object_or_404(Hubs, pk=hub_id)
                hub.manager = manager
                hub.country = country
                hub.name = name
                hub.save()
            except KeyError as e:
                print e
                print "KeyError POST hub_update POST"
                return HttpResponseServerError(request)

            return JsonResponse({'code': '200',
                                 'msg': 'hub updated',
                                 'id': hub_id,
                                 })

        else:
            try:
                hub_id = request.GET['id']
                hub = get_object_or_404(Hubs, pk=hub_id)
                hub.delete()
            except KeyError as e:
                print e
                print "KeyError hub_update_delete GET"
                return HttpResponseServerError(request)

            return JsonResponse({'code': '200',
                                 'msg': 'hub deleted',
                                 'id': hub_id,
                                 })
    else:
        raise Http404("Not Found")


def hub_search(request):
    if request.method == 'POST':
        option = request.POST['option']
        search_text = request.POST['search_txt']
        if option == 'hub':
            hubs = Hubs.objects.filter(name__contains=search_text)
            context = {'hubs': hubs}
            if not hubs:
                # print "Hubs.DoesNotExist at hub_search POST" + e.args
                context = {'error': 'Hub not found'}
                # return render(request, 'hubs/dashboard.html', context)

            return render(request, 'hubs/dashboard.html', context)

        if option == 'manager':
            hubs = Hubs.objects.filter(manager__contains=search_text)
            context = {'hubs': hubs}
            if not hubs:
                # print "Hubs.DoesNotExist at hub_search POST" + e.args
                context = {'error': 'Manager not found'}
                # return render(request, 'hubs/dashboard.html', context)

            return render(request, 'hubs/dashboard.html', context)
        else:
            print "Nor HUB nor MANAGER"
            return HttpResponse('Error')
    else:
        raise Http404(request)


def hub_detail(request, pk):
    hub = get_object_or_404(Hubs, pk=pk)
    bank_accounts = hub.bank_accounts()
    cash_accounts = hub.cash_accounts()
    curr = Currency.objects.all()
    context = {'hub': hub,
               'banks': bank_accounts,
               'cash': cash_accounts,
               'curr': curr,
               }
    return render(request, 'hubs/detail.html', context)
    # response = "Hub detail: " + pk
    # return HttpResponse(response)


@csrf_exempt
def hub_add_account(request, pk):
    if request.is_ajax():
        # POST method for creating a new object
        if request.method == 'POST':

            try:
                a_type = request.POST['account_type']
                b = request.POST['balance']
                curr = request.POST['currency']
                currency = Currency.objects.filter(name=curr)
                hub = get_object_or_404(Hubs, pk=pk)
                if a_type == 'b':
                    bank = request.POST['bank_name']
                    number = request.POST['number']
                    new_acc = Account(account_type=a_type, balance=b, currency=currency[0],
                                      bank_name=bank, number=number, owner=hub)
                else:
                    new_acc = Account(account_type=a_type, balance=b, currency=currency[0],
                                      owner=hub)

            except KeyError, e:
                print "Key Error account_new_get POST"
                print e
                return HttpResponseServerError(request)
            except Exception as e:
                print "Turbo Exception account_new_get GET"
                print e.args
                return HttpResponseServerError(request)

            new_acc.save()

            return JsonResponse({'code': '200',
                                 'msg': 'all cool',
                                 'pk': new_acc.pk},
                                )

        # GET method for retrieving an object
        elif request.method == 'GET':
            try:
                account_id = request.GET['id']
                print account_id
                account = get_object_or_404(Account, pk=account_id)
                # account = Account.objects.get(pk=account_id)
                currency = Currency.objects.get(pk=account.currency.pk)
                json_account = {'id': account.pk,
                                'type': account.account_type,
                                'bank': account.bank_name,
                                'balance': account.balance,
                                'currency': currency.name,
                                'number': account.number,
                                }

            except KeyError as e:
                print "Key Error account_new_get GET"
                print type(e)
                return HttpResponseServerError(request)

            return JsonResponse(json_account)

        # The rest of the methods are not supported
        else:
            raise Http404(request)
    else:
        raise Http404(request)


@csrf_exempt
def hub_account_update_delete(request, pk):
    if request.is_ajax():
        if request.method == 'POST':
            try:
                account_id = request.POST['id']
                a_type = request.POST['account_type']
                b = request.POST['balance']
                curr = request.POST['currency']
                currency = Currency.objects.filter(name=curr)
                account = Account.objects.get(pk=account_id)
                account.account_type = a_type
                account.balance = b
                account.currency = currency[0]
                if a_type == 'b':
                    bank = request.POST['bank_name']
                    number = request.POST['number']

                    account.bank_name = bank
                    account.number = number

                account.save()

                return JsonResponse({'code': '200',
                                     'msg': 'all cool',
                                     'pk': account.pk},
                                    )

            except (KeyError, Exception) as e:
                print "KeyError/ Exception account_update_delete POST"
                print type(e)
                print e.args
                return HttpResponseServerError(request)

        elif request.method == 'GET':
            try:
                account_id = request.GET['id']
                account = Account.objects.get(pk=account_id)
                account.delete()

                return JsonResponse({'code': '200',
                                     'msg': 'account deleted',
                                     'pk': account_id},
                                    )
            except (KeyError, Exception) as e:
                print "Key Error/Exception account_update_delete GET"
                print type(e)
                return HttpResponseServerError(request)

        else:
            raise Http404(request)
    else:
        raise Http404(request)


def account_detail(request, pk):
    account = get_object_or_404(Account, pk=pk)
    category = Category.objects.all()
    context = {'a': account,
               'category': category,
               }
    return render(request, 'hubs/b_detail.html', context)

gvi/hubs/templates/hubs/b_detail.html
<!-- dashboard -->

{% extends "base_generic.html" %}

{% block menubar %}
    <p class="navbar-text"><a href="{% url 'hubs:hub_detail' a.owner.id %}" style="color: black; text-decoration: none;"> <button class="btn btn-default btn-sm glyphicon glyphicon-menu-left" type="button" id="btnHubs"> {{ a.owner.name }}</button></a></p>
{% endblock %}

{% block content %}
    <div class="row col-xs-offset-1">
        <!-- Hub info -->
        <div class="row">
            <div class="col-xs-12">
                <h1>
                    <div id="hubname">Balance Details</div>
                </h1>
                <h4>
                    <div id="hubinfo" style="padding-left: 10px;">
                        <ul class="list-unstyled">
                            {% if a.account_type == 'b' %}
                                <li>Currency: {{ a.currency }}</li>
                                <li>Bank: {{ a.bank_name }}</li>
                                <li>Account No. {{ a.number }}</li>
                            {% else %}
                                <li>Currency: {{ a.currency }}</li>
                            {% endif %}

                            {% if a.balance < 0 %}
                                <li>Remaining Budget:<label style="color: red;">{{ a.balance }}</label></li>
                            {% else %}
                                <li>Remaining Budget: {{ a.balance }}</li>
                            {% endif %}

                            <li>Total Expenses: {{ a.expenses }}</li>
                        </ul>
                    </div>
                </h4>

            </div>
        </div>
        <!-- /.row Hub info -->

        <!-- Form data to backend -->
        <form action="{% url 'transactions:search_transactions' %}" method="post">
            {% csrf_token %}

            <!-- Category title -->
            <div class="row">
                <div class="col-xs-8">
                    <div class="col-xs-1">
                        <label class="select-title">Enable</label>
                    </div>
                    <div class="col-xs-1">
                        <label class="select-title">Category</label>
                    </div>
                </div>
            </div>
            <!-- /.row Category/Subcategory title -->

            <!-- Category -->
            <div class="row">
                <div class="col-xs-8">
                    <div class="col-xs-1 checkbox">
                        <div class="pull-right">
                            <label class="select-title">
                                <input type="checkbox" id="enableCategory" name="enableCategory">
                            </label>
                        </div>
                    </div>
                    <div class="col-xs-11 pull-left">
                        <div class="form-group">
                            <select class="form-control" id="categorySelect" name="categorySelect">
                                {% for a in category %}
                                    <option>{{ a.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.row Category -->

            <!-- Subcategory title -->
            <div class="row">
                <div class="col-xs-8">
                    <div class="col-xs-1 col-xs-offset-1">
                        <label class="select-title">Subcategory</label>
                    </div>
                </div>
            </div>
            <!-- /.row Subcategory title -->

            <!-- Subcategory -->
            <div class="row">
                <div class="col-xs-8">
                    <div class="col-xs-1 checkbox">
                        <div class="pull-right">
                            <label class="select-title">
                                <input type="checkbox" name="enableSubcategory" id="enableSubcategory">
                            </label>
                        </div>
                    </div>
                    <div class="col-xs-11 pull-left">
                        <div class="form-group">
                            <select class="form-control" id="subcategorySelect" name="subcategorySelect">

                                    <option></option>

                            </select>
                        </div>
                    </div>
                    <!-- /.col-xs-4 -->
                </div>
            </div>
            <!-- /.row Subcategory -->
            <div class="row">
                <div class="col-xs-8">
                    <div class="alert alert-danger" role="alert" id="dateError" name="dateError" hidden="true">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <strong>Error:</strong> Initial date is greater than end date.
                    </div>
                </div>
            </div>

            <!-- To - From title -->
            <div class="row">
                <div class="col-xs-8">
                    <div class="col-xs-1">
                        <label class="select-title">From</label>
                    </div>
                    <div class="col-xs-1 col-xs-offset-7">
                        <div class="pull-left">
                            <label class="select-title">To</label>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.row To - From title -->

            <!-- Date data and search button -->
            <div class="row">
                <div class="col-xs-8">
                    <div class="col-xs-4">
                        <div class="form-group">
                            <div class='input-group date' id='datetimepickerFrom'>
                                <input type='text' class="form-control" id="fromDate" name="fromDate" readonly/>
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                 </span>
                            </div>
                        </div>
                    </div>


                    <div class="col-xs-4">
                        <hr class="horizontal-separator">
                    </div>

                    <div class="col-xs-4">
                        <div class="form-group">
                            <div class='input-group date' id='datetimepickerTo'>
                                <input type='text' class="form-control" id="toDate" name="toDate" readonly/>
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                 </span>
                            </div>
                        </div>
                    </div>

                </div>
                <button type="submit" class="btn btn-info pull-left">
                    <span class="glyphicon glyphicon-search" aria-hidden="true"></span> search
                </button>
            </div><br>
            <!-- /.row Date data and search button -->
        </form>
        <!-- Form data to backend -->

        <!-- Transaction table -->
        <div class="row">
            <div class="col-md-10">
                <p class="tableTitle">Transactions:</p>
                <table class="table table-hover">
                    <tr>
                        <th>Date</th>
                        <th>Code</th>
                        <th>Category</th>
                        <th>Subcategory</th>
                        <th>Comment</th>
                        <th>Amount</th>
                        <th>Type</th>
                        <th>Balance</th>
                        <th>Edit</th>
                    </tr>

                    <!-- For to fill info about each account -->
                    {% for a in transactions %}
                        <tr id="{{ a.id }}">
                            <td hidden id="pk">{{ a.id }}</td>
                            <td>{{ a.date }}</td>
                            <td>{{ a.category.number }}</td>
                            <td>{{ a.category.name }}</td>
                            <td>{{ a.subcategory.name }}</td>
                            <td>{{ a.comment }}</td>
                            <td>{{ a.amount }}</td>
                            {% if a.transaction_type == 'i' %}
                                <td>+ Money In</td>
                            {% else %}
                                <td>- Money Out</td>
                            {% endif %}
                            {% if a.balance < 0 %}
                                <td style="color: red">{{ a.balance }}</td>
                            {% else %}
                                <td>{{ a.balance }}</td>
                            {% endif %}
                            <td><a class="glyphicon glyphicon-pencil" data-toggle="modal" data-target="#modalEditTransaction" onclick="editTransaction({{ a.id }})"></a></td>
                        </tr>
                    {% endfor %}
                    <!-- ****************************************-->

                </table>
            </div>
        </div><!-- /.row Transaction table -->

    </div>

{% endblock %}

gvi/hubs/templates/hubs/balance_detail.html
<!-- dashboard -->

{% extends "base_generic.html" %}

{% block menubar %}

{% endblock %}

{% block content %}
    <div class="row col-xs-offset-1">
        <!-- Hub info -->
        <div class="row">
            <div class="col-xs-12">
                <h1>
                    <div id="hubname">Balance Details</div>
                </h1>
                <h4>
                    <div id="hubinfo">
                        <ul class="list-unstyled">
                            {% if a.account_type == 'b' %}
                                <li>Currency: {{ a.currency }}</li>
                                <li>Bank: {{ a.bank_name }}</li>
                                <li>Account No. {{ a.number }}</li>
                            {% else %}
                                <li>Currency: {{ a.currency }}</li>
                            {% endif %}

                            <li>Initial Budget: $15,000</li>
                            <li>Remaining Budget: $10,000</li>
                            <li>Total Expenses: $5,000</li>
                        </ul>
                    </div>
                </h4>

            </div>
        </div>
        <!-- /.row Hub info -->

        <!-- Form data to backend -->
        <form action="{% url 'transactions:search_transactions' %}" method="post">
            {% csrf_token %}

            <!-- Category title -->
            <div class="row">
                <div class="col-xs-8">
                    <div class="col-xs-1">
                        <label class="select-title">Enable</label>
                    </div>
                    <div class="col-xs-1">
                        <label class="select-title">Category</label>
                    </div>
                </div>
            </div>
            <!-- /.row Category/Subcategory title -->

            <!-- Category -->
            <div class="row">
                <div class="col-xs-8">
                    <div class="col-xs-1 checkbox">
                        <div class="pull-right">
                            <label class="select-title">
                                <input type="checkbox" id="enableCategory" name="enableCategory">
                            </label>
                        </div>
                    </div>
                    <div class="col-xs-11 pull-left">
                        <div class="form-group">
                            <select class="form-control" id="categorySelect" name="categorySelect">
                                {% for a in category %}
                                    <option>{{ a.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.row Category -->

            <!-- Subcategory title -->
            <div class="row">
                <div class="col-xs-8">
                    <div class="col-xs-1 col-xs-offset-1">
                        <label class="select-title">Subcategory</label>
                    </div>
                </div>
            </div>
            <!-- /.row Subcategory title -->

            <!-- Subcategory -->
            <div class="row">
                <div class="col-xs-8">
                    <div class="col-xs-1 checkbox">
                        <div class="pull-right">
                            <label class="select-title">
                                <input type="checkbox" name="enableSubcategory" id="enableSubcategory">
                            </label>
                        </div>
                    </div>
                    <div class="col-xs-11 pull-left">
                        <div class="form-group">
                            <select class="form-control" id="subcategorySelect" name="subcategorySelect">
                                {% for a in subcategory %}
                                    <option>{{ a.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <!-- /.col-xs-4 -->
                </div>
            </div>
            <!-- /.row Subcategory -->
            <div class="row">
                <div class="col-xs-8">
                    <div class="alert alert-danger" role="alert" id="dateError" name="dateError" hidden="true">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <strong>Error:</strong> Initial date is greater than end date.
                    </div>
                </div>
            </div>

            <!-- To - From title -->
            <div class="row">
                <div class="col-xs-8">
                    <div class="col-xs-1">
                        <label class="select-title">From</label>
                    </div>
                    <div class="col-xs-1 col-xs-offset-7">
                        <div class="pull-left">
                            <label class="select-title">To</label>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.row To - From title -->

            <!-- Date data and search button -->
            <div class="row">
                <div class="col-xs-8">
                    <div class="col-xs-4">
                        <div class="form-group">
                            <div class='input-group date' id='datetimepickerFrom'>
                                <input type='text' class="form-control" id="fromDate" name="fromDate" readonly/>
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                 </span>
                            </div>
                        </div>
                    </div>


                    <div class="col-xs-4">
                        <hr class="horizontal-separator">
                    </div>

                    <div class="col-xs-4">
                        <div class="form-group">
                            <div class='input-group date' id='datetimepickerTo'>
                                <input type='text' class="form-control" id="toDate" name="toDate" readonly/>
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                 </span>
                            </div>
                        </div>
                    </div>

                </div>
                <button type="submit" class="btn btn-info pull-left">
                    <span class="glyphicon glyphicon-search" aria-hidden="true"></span> search
                </button>
            </div>
            <!-- /.row Date data and search button -->
        </form>
        <!-- Form data to backend -->

        <!-- Transaction table -->
        <div class="row">
            <div class="col-xs-8">
                <p class="tableTitle">Bank Accounts:</p>
                <table class="table table-hover">
                    <tr>
                        <th>Date</th>
                        <th>Code</th>
                        <th>Category</th>
                        <th>Subcategory</th>
                        <th>Comment</th>
                        <th>Amount</th>
                        <th>Balance</th>
                        <th>Edit</th>
                    </tr>

                    <!-- For to fill info about each account -->
                    {% for a in transactions %}
                        <tr>
                            <td>{{ a.date }}</td>
                            <td>{{ a.category.number }}</td>
                            <td>{{ a.category.name }}</td>
                            <td>{{ a.subcategory.name }}</td>
                            <td>{{ a.comment }}</td>
                            <td>{{ a.amount }}</td>
                            <td>{{ a.balance }}</td>
                            <td><a class="glyphicon glyphicon-pencil" data-toggle="modal"
                                   data-target="#modalEditTransaction" onclick="editTransaction()"></a></td>
                        </tr>
                    {% endfor %}
                    <!-- ****************************************-->

                </table>
            </div>
        </div><!-- /.row Transaction table -->

    </div>
{% endblock %}