gvi/gvi/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^reports/', include('reports.urls', namespace='reports', app_name='reports')),
    url(r'^budgets/', include('budgets.urls', namespace='budgets', app_name='budgets')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts', app_name='accounts')),
    url(r'^transactions/', include('transactions.urls', namespace='transactions', app_name='transactions')),
    url(r'^hubs/', include('hubs.urls', namespace='hubs', app_name='hubs')),
    url(r'^users/', include('users_m.urls', namespace='users_m', app_name='users_m')),
    url(r'^admin/', include(admin.site.urls)),
]

gvi/hubs/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^hub/search/$', views.hub_search, name='hub_search'),
    url(r'^hub/$', views.add_get_hub, name='hub'),
    url(r'^hub/(?P<pk>\d+)/$', views.hub_detail, name='hub_detail'),
    url(r'^hub/(?P<pk>\d+)/create_account/$', views.hub_add_account, name='hub_add_account'),
    url(r'^hub/(?P<pk>\d+)/change_account/$', views.hub_account_update_delete, name='hub_update_account'),
    url(r'^change_hub/$', views.hub_update_delete, name='hub_update_delete'),
    url(r'^hub/account/(?P<pk>\d+)/$', views.account_detail, name='account_detail'),
]

gvi/users_m/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^user_login/$', views.app_login, name='user_login'),
    url(r'^user_logout/$', views.app_logout, name='user_logout'),
]

gvi/templates/base_generic.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head lang="en">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Gvi Accounting System</title>
    <script src="{% static 'js/jquery-1.11.3.min.js' %}"></script>
    <script src="{% static 'js/moment.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/bootstrap-datetimepicker.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/datepicker.min.css' %}">

    <script src="{% static 'js/app.js' %}"></script>
    <script src="{% static 'js/hubs.js' %}"></script>
    <script src="{% static 'js/transaction.js' %}"></script>
    <script src="{% static 'js/budgets.js' %}"></script>
</head>
<body>
<div class="container-fluid">

    <div class="row">
        {% block sidebar %}
            <div class="col-xs-2" id="sidebar">
                <img src="{% static 'img/gvi_logo.png' %}" id="logo">
                <div id="user">Hello {{ request.user }}</div>
                <ul class="nav nav-pills nav-stacked">
                    <li role="presentation"><a href="{% url 'accounts:index' %}">Accounts</a></li>
                    <li role="presentation"><a href="{% url 'hubs:index' %}">Hubs</a></li>
                    <li role="presentation"><a href="{% url 'budgets:index' %}">Budgets</a></li>
                    <li role="presentation"><a href="{% url 'transactions:index' %}">Transactions</a></li>
                    <li role="presentation"><a href="{% url 'budgets:index' %}">Reports</a></li>
                    <!--<li role="presentation"><a href="#">Settings <i class="glyphicon glyphicon-cog"></i></a></li>-->
                    <li role="presentation"><a href="{% url 'users_m:user_logout' %}">Logout <i class="glyphicon glyphicon-log-out"></i></a></li>
                </ul>

            </div>
        {% endblock %}

        <div class="col-xs-10">
            <div class="row">

                <nav class="navbar navbar-default">
                    <div class="container-fluid">
                        <div class="navbar-header">
                            {% block menubar %}
                            {% endblock %}
                        </div>
                    </div>
                </nav>

                {% block content %}
                {% endblock %}

            </div>
        </div>



    </div>
</div>


</body>
</html>